### ISSUE TITLE
Instructor Feedback Week 9

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [MadJavaEntFall2017/fantastic-umbrella#3]
Hey Gang, remember to add:
- [x] problem statement
- [x] proposed solution
- [x] outline of the capability the service will provide- this could be the various URIs
- [x] project plan
- [x] add a link to your repository to the list of team projects in the student repo

**Comment by brookeswanson** [comment]
The branch project-description includes the requested changes.  I have submitted a pull request and the master branch of the project should reflect the changes later this evening.
